// frontend/src/components/v2/Select/DatabaseSelect.vue
<!-- i18n: vue-i18n | use t("key") from useI18n() -->
<template>
  <RemoteResourceSelector
    v-bind="$attrs"
    class="bb-database-select"
    :multiple="multiple"
    :disabled="disabled"
    :size="size"
    :value="value"
    :render-label="renderLabel"
    :render-tag="renderTag"
    :additional-options="additionalOptions"
    :search="handleSearch"
    :filter="filter"
    @update:value="(val) => $emit('update:value', val)"
  />
</template>

<script lang="tsx" setup>
import { computedAsync } from "@vueuse/core";
import { computed } from "vue";
import { RichDatabaseName } from "@/components/v2";
import { useActuatorV1Store, useDatabaseV1Store } from "@/store";
import { type Engine } from "@/types/proto-es/v1/common_pb";
import type { Database } from "@/types/proto-es/v1/database_service_pb";
import { extractDatabaseResourceName } from "@/utils";
import RemoteResourceSelector from "./RemoteResourceSelector/index.vue";
import type {
  ResourceSelectOption,
  SelectSize,
} from "./RemoteResourceSelector/types";
import {
  getRenderLabelFunc,
  getRenderTagFunc,
} from "./RemoteResourceSelector/utils";

const props = withDefaults(
  defineProps<{
    value?: string | string[] | undefined;
    environmentName?: string;
    projectName?: string;
    allowedEngineTypeList?: Engine[];
    filter?: (database: Database) => boolean;
    multiple?: boolean;
    disabled?: boolean;
    size?: SelectSize;
    showInstance?: boolean;
  }>(),
  {
    // empty equals no limit.
    allowedEngineTypeList: () => [],
    showInstance: true,
  }
);

defineEmits<{
  (event: "update:value", value: string[] | string | undefined): void;
}>();

const databaseStore = useDatabaseV1Store();
const actuatorStore = useActuatorV1Store();

const getOption = (db: Database) => {
  return {
    resource: db,
    value: db.name,
    label: extractDatabaseResourceName(db.name).databaseName,
  };
};

const additionalOptions = computedAsync(async () => {
  const options: ResourceSelectOption<Database>[] = [];

  let databaseNames: string[] = [];
  if (Array.isArray(props.value)) {
    databaseNames = props.value;
  } else if (props.value) {
    databaseNames = [props.value];
  }

  const databases = await databaseStore.batchGetOrFetchDatabases(databaseNames);
  options.push(...databases.map(getOption));

  return options;
}, []);

const handleSearch = async (params: {
  search: string;
  pageToken: string;
  pageSize: number;
}) => {
  const { databases, nextPageToken } = await databaseStore.fetchDatabases({
    parent: props.projectName ?? actuatorStore.workspaceResourceName,
    filter: {
      environment: props.environmentName,
      engines: props.allowedEngineTypeList,
      query: params.search,
    },
    pageToken: params.pageToken,
    pageSize: params.pageSize,
    silent: true,
  });
  return {
    nextPageToken,
    options: databases.map(getOption),
  };
};

const customLabel = (database: Database, keyword: string) => {
  return (
    <RichDatabaseName
      database={database}
      keyword={keyword}
      showProject={false}
      showInstance={props.showInstance}
      showArrow={props.showInstance}
    />
  );
};

const renderLabel = computed(() => {
  return getRenderLabelFunc({
    multiple: props.multiple,
    customLabel,
    showResourceName: true,
  });
});

const renderTag = computed(() => {
  return getRenderTagFunc({
    multiple: props.multiple,
    disabled: props.disabled,
    size: props.size,
    customLabel,
  });
});
</script>

// frontend/src/react/components/DatabaseSelect.tsx
// i18n: i18next | use t("key") from useTranslation()
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { EngineIcon } from "@/react/components/EngineIcon";
import { EnvironmentLabel } from "@/react/components/EnvironmentLabel";
import { Combobox } from "@/react/components/ui/combobox";
import { useActuatorV1Store, useDatabaseV1Store } from "@/store";
import type { Engine } from "@/types/proto-es/v1/common_pb";
import type { Database } from "@/types/proto-es/v1/database_service_pb";
import {
  extractDatabaseResourceName,
  getDatabaseEnvironment,
  getDefaultPagination,
  getInstanceResource,
} from "@/utils";

export interface DatabaseSelectProps {
  value: string;
  onChange: (value: string, database: Database | undefined) => void;
  placeholder?: string;
  disabled?: boolean;
  className?: string;
  projectName?: string;
  environmentName?: string;
  allowedEngineTypeList?: Engine[];
}

export function DatabaseSelect({
  value,
  onChange,
  placeholder,
  disabled,
  className,
  projectName,
  environmentName,
  allowedEngineTypeList,
}: DatabaseSelectProps) {
  const { t } = useTranslation();
  const databaseStore = useDatabaseV1Store();
  const actuatorStore = useActuatorV1Store();
  const [databases, setDatabases] = useState<Database[]>([]);

  // Stabilize engines array to avoid re-fetching on every render
  const enginesRef = useRef(allowedEngineTypeList);
  const stableEngines = useMemo(() => {
    const prev = enginesRef.current;
    if (
      prev &&
      allowedEngineTypeList &&
      prev.length === allowedEngineTypeList.length &&
      prev.every((e, i) => e === allowedEngineTypeList[i])
    ) {
      return prev;
    }
    enginesRef.current = allowedEngineTypeList;
    return allowedEngineTypeList;
  }, [allowedEngineTypeList]);

  const fetchDatabases = useCallback(
    (query: string) => {
      databaseStore
        .fetchDatabases({
          parent: projectName ?? actuatorStore.workspaceResourceName,
          filter: {
            environment: environmentName,
            engines: stableEngines,
            query,
          },
          pageSize: getDefaultPagination(),
          silent: true,
        })
        .then((result) => setDatabases(result.databases));
    },
    [databaseStore, projectName, environmentName, stableEngines, actuatorStore]
  );

  useEffect(() => {
    fetchDatabases("");
  }, [fetchDatabases]);

  const handleChange = useCallback(
    (name: string) => {
      const db = databases.find((d) => d.name === name);
      onChange(name, db);
    },
    [databases, onChange]
  );

  return (
    <Combobox
      value={value}
      onChange={handleChange}
      placeholder={placeholder ?? t("database.select")}
      noResultsText={t("common.no-data")}
      onSearch={fetchDatabases}
      disabled={disabled}
      className={className}
      renderValue={(opt) => {
        const db = databases.find((d) => d.name === opt.value);
        if (!db) return opt.label;
        const inst = getInstanceResource(db);
        return (
          <span className="flex items-center gap-1.5 truncate">
            <EngineIcon engine={inst.engine} className="h-4 w-4" />
            {extractDatabaseResourceName(db.name).databaseName}
          </span>
        );
      }}
      options={databases.map((db) => {
        const inst = getInstanceResource(db);
        return {
          value: db.name,
          label: extractDatabaseResourceName(db.name).databaseName,
          description: extractDatabaseResourceName(db.name).instance,
          render: () => (
            <div className="flex flex-col gap-0.5">
              <div className="flex items-center gap-1.5">
                {inst.title && (
                  <>
                    <EngineIcon engine={inst.engine} className="h-4 w-4" />
                    <span>{inst.title}</span>
                    <span className="text-control-placeholder">&gt;</span>
                  </>
                )}
                <EnvironmentLabel
                  environmentName={getDatabaseEnvironment(db).name}
                />
                <span className="text-control-placeholder">&gt;</span>
                <span>{extractDatabaseResourceName(db.name).databaseName}</span>
              </div>
              <span className="text-xs text-control-placeholder">
                {extractDatabaseResourceName(db.name).instance}/databases/
                {extractDatabaseResourceName(db.name).databaseName}
              </span>
            </div>
          ),
        };
      })}
    />
  );
}
