// frontend/src/components/LearnMoreLink.vue
<!-- i18n: vue-i18n | use t("key") from useI18n() -->
<template>
  <a
    v-if="url"
    class="inline-flex items-center"
    :class="[color === 'normal' ? 'normal-link' : 'light-link']"
    :href="url"
    :target="external ? '__BLANK' : ''"
  >
    {{ text }}
    <ExternalLinkIcon v-if="external" class="w-4 h-4 ml-1" />
  </a>
</template>

<script lang="ts" setup>
import { ExternalLinkIcon } from "lucide-vue-next";
import { computed } from "vue";
import { t } from "@/plugins/i18n";

const props = withDefaults(
  defineProps<{
    url: string;
    text?: string;
    color?: "normal" | "light";
  }>(),
  {
    color: "normal",
    text: () => t("common.learn-more"),
  }
);

const external = computed(() => props.url.startsWith("http"));
</script>

// frontend/src/react/components/LearnMoreLink.tsx
// i18n: i18next | use t("key") from useTranslation()
import { ExternalLink } from "lucide-react";
import { useTranslation } from "react-i18next";
import { cn } from "@/react/lib/utils";

interface LearnMoreLinkProps {
  href: string;
  className?: string;
}

export function LearnMoreLink({ href, className }: LearnMoreLinkProps) {
  const { t } = useTranslation();
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className={cn(
        "inline-flex items-center gap-x-0.5 hover:underline",
        className
      )}
    >
      {t("common.learn-more")}
      <ExternalLink className="w-3 h-3" />
    </a>
  );
}
